Recaptcha.configure do |config|
  config.site_key  = '6Lc54jQUAAAAAKwSe7DLfrjyBMe-TkkQcZ4oJTvi' #keys are generated by https://www.google.com/recaptcha/admin#list 
  config.secret_key = '6Lc54jQUAAAAAMwYbtfc1yXjG5QGC5OslEY91v6E' #using ascratech mail id
end